name: Create release artifact

on:
  release:
    types:
      - published

jobs:
  build_and_upload:
    name: Build and upload release artifact

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: 'neon-plugins.jar'
          asset_path: 'target/neon-plugins.jar'
          asset_content_type: 'application/java-archive'
